// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAermC5rP6hgrw1Mzy6577IjS6WuTthVC4',
    appId: '1:266331724120:web:7089e18d1e7b13e834ed2d',
    messagingSenderId: '266331724120',
    projectId: 'team-project-6af55',
    authDomain: 'team-project-6af55.firebaseapp.com',
    storageBucket: 'team-project-6af55.firebasestorage.app',
    measurementId: 'G-PMSFR84V3S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAOc2hq_6L3wKeQ2uKnfuCpwIadn7XfEc',
    appId: '1:266331724120:android:44f7560909b40c5f34ed2d',
    messagingSenderId: '266331724120',
    projectId: 'team-project-6af55',
    storageBucket: 'team-project-6af55.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE8M30OEltU5X7888oO01_gEae9uixgAw',
    appId: '1:266331724120:ios:fdcce54848b220df34ed2d',
    messagingSenderId: '266331724120',
    projectId: 'team-project-6af55',
    storageBucket: 'team-project-6af55.firebasestorage.app',
    iosBundleId: 'com.example.dripsWater',
  );
}
